image: barichello/godot-ci:3.4

variables:
  EXPORT_NAME:gonote

stages:
  -export 
  -deploy

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
